script:
- prompt: "Are there any issues with my app running in the calc-app namespace? Anything of interest in the logs?"
setup: "setup.sh"
verifier: "verify.sh"
cleanup: "cleanup.sh"
difficulty: "medium"
expect:
- contains: "division by zero"
