apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
      version: green
  template:
    metadata:
      labels:
        app: checkout-service
        version: green
    spec:
      containers:
      - name: app
        image: nginx:1.26 # Use a different image tag to represent a new version
        ports:
        - containerPort: 80