apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  selector:
    # This selector initially targets the 'blue' version
    app: checkout-service
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80