script:
- prompt: |
    In the multi-container-logging namespace, run a pod called communication-pod with two containers:
    1. A 'web-server' nginx instance that serves traffic
    2. A 'logger' busybox instance that processes those logs from a shared volume, 'logs-volume' with 'tail -f /var/log/nginx/access.log'

    Both containers should mount logs-volume at '/var/log/nginx'.
    The logger should only start once the web server is ready. The pod should be considered ready when the web server is serving traffic.
setup: "setup.sh"
verifier: "verify.sh"
cleanup: "cleanup.sh"
difficulty: "medium"