script:
- prompt: |
    Create a pod named 'communication-pod' in the 'multi-container-test' namespace with two containers: 1. A 'web' container using nginx:alpine image that serves web content on port 80. 2. A 'logger' container using busybox image that monitors the nginx access logs. The containers should share a volume named 'logs-volume' where nginx writes its access logs. The web container should be ready when port 80 is available. The logger container should start only after the web container is ready.
setup: "setup.sh"
verifier: "verify.sh"
cleanup: "cleanup.sh"
difficulty: "medium"