apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: webapp-backend
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: api-server
          image: nginx:alpine
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "Starting memory-intensive application..."
              # Simulate a memory-hungry application
              dd if=/dev/zero of=/tmp/memory-hog bs=1M count=150 &
              nginx -g 'daemon off;'
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi" # This is insufficient for the 150MB allocation above
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
