apiVersion: v1
kind: Namespace
metadata:
  name: computer
  labels:
    name: computer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: normal-user
  namespace: computer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: computer
  name: reader-all-but-secrets
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status", "configmaps", "persistentvolumeclaims", "replicationcontrollers", "resourcequotas", "limitranges", "endpoints", "events", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["deployments", "daemonsets", "replicasets", "ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: normal-user-reader-binding
  namespace: computer
subjects:
- kind: ServiceAccount
  name: normal-user
  namespace: computer
roleRef:
  kind: Role
  name: reader-all-but-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader-cluster-resources
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: normal-user-cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: normal-user
  namespace: computer
roleRef:
  kind: ClusterRole
  name: reader-cluster-resources
  apiGroup: rbac.authorization.k8s.io 