apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: normal-user-cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: normal-user
  namespace: computer
roleRef:
  kind: ClusterRole
  name: reader-cluster-resources
  apiGroup: rbac.authorization.k8s.io 